src/app/views/account.py
from flask import render_template, request, url_for, session, redirect, flash, Blueprint

from models import User
from views.top import show_top


blueprint = Blueprint('account', __name__)

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method =='POST':
        try:
            user_id = request.form.get('user_id')
            print('User is {User}')
            print('test is {User.id}')
            user_info = User.query.filter_by(user_id = user_id).first()
            if user_info is None:
                flash('ユーザIDが違います。', 'error')
            elif not user_info.password == request.form.get('password'):
                flash('パスワードが違います。', 'error')
            else:
                session['logged_in'] = True
                session['user_table_id'] = user_info.id
                session['user_id'] = user_info.user_id
                session['name'] = user_info.name
                session['undergraduate'] = user_info.undergraduate
                flash('ログインしました。', 'success')
                flash('ようこそ'+session['name']+'さん！', 'success')
                return show_top(session.get('name'), session.get('undergraduate'))
        except ValueError:
            flash('適切なユーザIDを入力してください', 'error')
    return render_template('account/login.html')

@blueprint.route('/logout')
def logout():
    session.pop('logged_in', None)
    session.clear()
    flash('ログアウトしました。', 'success')
    return redirect(url_for('account.login'))

src/app/views/details.py
from flask import render_template, request, session, Blueprint

from models import Book
from database import db
from views import account, search


blueprint = Blueprint('details', __name__)

@blueprint.route('/<string:id>', methods=['POST'])
def show_details(id):
    book_info = Book.query.get(id)
    global before_url
    before_url = request.referrer
    return render_template('details/details.html', book_info=book_info)

@blueprint.route('/back')
def back_before_url():
    judge = before_url[(before_url.rfind('/')):]
    if judge == '/' or judge == '/back':
        undergraduate = session.get('undergraduate')
        ranking = list(db.session.execute(account.t, {'undergraduate':undergraduate}))
        return render_template('top.html', name=session.get('name'), undergraduate=undergraduate, ranking=ranking)
    else:
        return render_template('search/result.html', categories=search.categories)

src/app/views/search.py
from flask import render_template, request, Blueprint
from sqlalchemy import or_

from models import Book
from lib.login_check import login_check


blueprint = Blueprint('search', __name__)

@blueprint.route('/')
@login_check
def window():
    return render_template('search/window.html')

@blueprint.route('/result', methods=['POST'])
@login_check
def search_result():
    search_category = request.form.get('search_category')
    search_word = request.form.get('search_word')
    global categories
    if not search_category and not search_word:
        categories = Book.query.order_by(Book.category.desc())
    elif not search_category:
        categories = Book.query.order_by(Book.category.desc()).filter(or_(Book.title.like(f'%\\{search_word}%'), Book.name.like(f'%\\{search_word}%')))
    elif not search_word:
        categories = Book.query.order_by(Book.category.desc()).filter(Book.category==search_category)
    else:
        categories = Book.query.order_by(Book.category.desc()).filter(Book.category==search_category).filter(Book.title.like(f'%\\{search_word}%'))
    return render_template('search/result.html', categories=categories)

src/app/views/top.py
from flask import render_template, session, Blueprint
from sqlalchemy.sql import text

from database import db
from lib.login_check import login_check


blueprint = Blueprint('top', __name__)

@blueprint.route('/')
@login_check
def show_top(name, undergraduate):
    global t
    t = text("\
        select b.id, b.title, b.name, b.category \
        from histories h \
            inner join books b \
                on h.book_id = b.id \
        where h.user_id in ( \
            select u.id \
            from users u \
            where u.undergraduate = :undergraduate)  \
        and h.datetime between date_sub(current_date, interval 30 day) and current_date \
        group by b.id, b.title, b.name, b.category  \
        order by count(h.id) desc \
        limit 0, 10; \
    ")
    gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
    if gakubu_search_result == []:
        if undergraduate=='経済学部':
            t = text("select id, title, name, category from books order by keizai limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        elif undergraduate=='法学部':
            t = text("select id, title, name, category from books order by hougaku limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        elif undergraduate=='理学部':
            t = text("select id, title, name, category from books order by rigaku limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        elif undergraduate=='工学部':
            t = text("select id, title, name, category from books order by kougaku limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        elif undergraduate=='文学部':
            t = text("select id, title, name, category from books order by bungaku limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        elif undergraduate=='医学部':
            t = text("select id, title, name, category from books order by igaku limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
        else:
            t = text("select id, title, name, category from books limit(10);")
            gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
    return render_template('top.html', name=name, undergraduate=undergraduate, ranking=gakubu_search_result)

@blueprint.route('/back')
@login_check
def back_top():
    undergraduate = session.get('undergraduate')
    gakubu_search_result = list(db.session.execute(t, {'undergraduate':undergraduate}))
    return render_template('top.html', name=session.get('name'), undergraduate=undergraduate, ranking=gakubu_search_result)

src/app/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <style>
        @import url('https://fonts.googleapis.com/css?family=Sawarabi+Gothic');

        body {
            font-family: 'Sawarabi Gothic', sans-seriff;
            background-color: #fbf8ef;
        }
        .Z_gen_lib{
            font-size: 1.5em;/* フォントサイズ */
            font-weight: bold;/* フォント太さ */
            padding-top: 1em;
            padding-bottom: 1em;
            margin-bottom: 2em;
            border-top: 3px solid #82ae46;/* 上の線 */
            border-bottom: 3px solid #82ae46;/* 下の線 */
            color: #82ae46;/* フォント色 */
            text-align: center;/* テキストの位置 */
        }
        a{
            text-decoration: none;
        }
        footer{
                    font-size: 1.0em;/* フォントサイズ */
                    font-weight: bold;/* フォント太さ */
                    padding-top: 1em;
                    padding-bottom: 1em;
                    margin-bottom: 2em;
                    border-top: 3px solid #82ae46;/* 上の線 */
                    border-bottom: 3px solid #82ae46;/* 下の線 */
                    color: #82ae46;/* フォント色 */
                    text-align: right;/* テキストの位置 */
                    margin-top: 120px;
                }
                a{
                    color:#82ae46 ;
                    font-size: 130%;
                }
    </style>
</head>
    <body>
        <header>
            <div>
                <h1 class="Z_gen_lib">Z_Generation_Library<br>福井大学図書館システム</h1>
                <h3 class="layout">
                {% for category, message in get_flashed_messages(with_categories=true) %}
                    {% if category == 'success' %}
                        <div style="background-color: #f8e58c;">{{ message }}</div>
                    {% elif category == 'error' %}
                        <div style="background-color: #ffc0cb;">{{ message }}</div>
                    {% endif %}
                {% endfor %}
                <div align = "right">
                <a href="{{url_for('top.back_top')}}">TOP</button>
                <a href="{{url_for('carts.index')}}">カート</button>
                <a href="{{url_for('account.logout')}}">ログアウト</a>
                </div>
                </h3>
            </div>
        </header>
        {% block body %}{% endblock %} 
        <footer>
            Produced by 稲毛商事
        </footer>  
    </body>
</html>

src/app/templates/top.html
{% extends "layout.html" %}
{% block title %}
TOP
{% endblock %}

{% block body %}
    <style>
        .window{
            font-size: 150%;
            text-align: center;
        }
        table {
        margin:auto;
        width:1000px;
        }
        .rank th {
        background-color: #b0ca71;
        border: solid 1px #ccc;
        color: #fff;
        padding: 10px;
        }
        .rank td {
        border: solid 1px #ccc;
        padding: 10px;
        text-align: center;
        }

        @media screen and (max-width: 640px) {
        .last td:last-child {
            border-bottom: solid 1px #ccc;
        }
        .rank {
            width: 80%;
            
        }
        .rank th,
        .rank td {
        border-bottom: none;
        display: block;
        }
        }
        h1{
            text-align: center;
        }
        .detail {
            position: relative;
            display: inline-block;
            padding: 0.25em 0.5em;
            text-decoration: none;
            color: #FFF;
            background: #b0ca71;/*背景色*/
            border-radius: 4px;/*角の丸み*/
            width: 100%;
            font-weight: bold;
            
        }
        .detail:hover{
        cursor:pointer;
        }
        .one{
            background-color: rgb(243, 229, 150);
            font-size: 20px;
            font-weight: bold;
        }
        .one_index{
            background-image:url(./f4-1.png);
            background-repeat: no-repeat;
            background-position: left center;
            padding-left: 110px;
        }
        .two{
            background-color: rgb(231, 229, 229);
            font-size: 17px;
            font-weight: bold;
        }
        .two_index{
             background-repeat: no-repeat;
            background-position: left center;
            padding-left: 110px;
        }
        .three{
            background-color: rgb(247, 188, 188);
            font-weight: bold;
        }
        .category{
            width: 10%;
        }
        .name{
            width:20%;
        }
        .detail_td{
            width: 12%;
        }
    </style>
    <a href="{{url_for('search.window')}}" class="window">検索画面へGO!</a>
    <h1>
        貸し出し数ランキング～{{ undergraduate }}編～
        <br>(
        <script>
            var before_day=new Date()
 
            before_day.setDate( before_day.getDate() - 30 );
            
            var before_day2 = before_day.getDate();
            var before_year = before_day.getFullYear();
            var before_month = before_day.getMonth()+1;
            document.write(before_year+"年"+before_month+"月"+before_day2+"日～");

            var today=new Date(); 
            var year = today.getFullYear();
            var month = today.getMonth()+1;
            var day = today.getDate();
            document.write(year+"年"+month+"月"+day+"日");
        </script>
        </script>
        )
    </h1>

    <table class="rank">
        <tr>
            <th>順位</th>
            <th>カテゴリ</th>
            <th>タイトル</th>
            <th>著者</th>
            <th>詳細はこちら</th>
        </tr>
            {% for row in ranking %}
    
                {% if loop.index ==1: %}
                    <tr class="one">
                        <br><td class="one_index"><i class="fas fa-crown"></i></br>
                {% elif loop.index ==2: %}
                    <tr class="two">
                        <td class="two_index">
                            
                {% elif loop.index ==3: %}
                    <tr class="three">
                        <td class="three_index">
                {% else %}
                    <tr class="normal">
                        <td class="normal_index">
                {% endif %}
                    {{ loop.index }}</td>
                <td class="category">{{ row.category }}</td>
                <td class="title">{{ row.title }}</td>
                <td class="name">{{ row.name }}</td>
                <form action="{{url_for('details.show_details', id=row.id)}}" method="POST">
                    <td class="detail_td"><button value="submit" class="detail">詳細</button></td>
                </form>
                </tr>
                <tr>
            {% endfor %}
    </table>
{% endblock %}