src/app/views/carts.py
from flask import render_template, request, url_for, session, redirect, flash, Blueprint
import datetime

from models import Book, History, User
from database import db
from lib.login_check import login_check


blueprint = Blueprint('carts', __name__)

@blueprint.route('/')
@login_check
def check_cart():
    return render_template('carts/index.html')

# カート画面を表示
@blueprint.route('/cart')
@login_check
def index():
    cart=session.get('cart')
    cart_details = list()
    if type(cart) is dict:
        for key in cart.keys():
            book=Book.query.get(key)
            cart_details.append({ 'id':key, 'name':book.name, 'title':book.title, 'category':book.category })
    return render_template('carts/index.html',cart_details=cart_details)

@blueprint.route('/create',methods=['POST'])
@login_check
def create():
    book_id=request.form.get('book_id') or ""
    cart=session.get('cart')
    if type(cart) is dict:
        cart[book_id]=Book.query.get(book_id).title
    else:
        cart={book_id:Book.query.get(book_id).title}
    session['cart']=cart
    flash('カートに追加しました','success')
    return redirect(url_for('carts.index'))

@blueprint.route('/<string:book_id>/delete',methods=['POST'])
@login_check
def delete(book_id):
    if book_id=='all':
        session.pop('cart',None)
    else:
        cart=session.get('cart')
        cart.pop(book_id,None)
        session['cart']=cart
    flash('本が削除されました','success')
    return redirect(url_for('carts.index'))

@blueprint.route('/insert')
@login_check
def insert():
    carts = session.get('cart')
    user_id = session.get('user_table_id')
    for book_id, title in carts.items():
        if book_id and title:
            history = History(
                book_id = book_id,
                user_id = user_id,
                datetime = datetime.date.today()
            )
            undergraduate = User.query.get(user_id).undergraduate
            if undergraduate == '経済学部':
                Book.query.get(book_id).keizai += 1
            elif undergraduate == '法学部':
                Book.query.get(book_id).hougaku += 1
            elif undergraduate == '理学部':
                Book.query.get(book_id).rigaku += 1
            elif undergraduate == '工学部':
                Book.query.get(book_id).kougaku += 1
            elif undergraduate == '文学部':
                Book.query.get(book_id).bungaku += 1
            elif undergraduate == '医学部':
                Book.query.get(book_id).igaku += 1
            db.session.add(history)
            db.session.commit()
        else:
            flash('最初からやり直してください', 'error')

    session.pop('cart', None)
    flash('本を借りました', 'success')
    return redirect(url_for('carts.index'))

src/app/views/details.py
from flask import render_template, request, session, Blueprint

from models import Book
from database import db
from views import account, search


blueprint = Blueprint('details', __name__)

@blueprint.route('/<string:id>', methods=['POST'])
def show_details(id):
    book_info = Book.query.get(id)
    global before_url
    before_url = request.referrer
    return render_template('details/details.html', book_info=book_info)

@blueprint.route('/back')
def back_before_url():
    judge = before_url[(before_url.rfind('/')):]
    if judge == '/' or judge == '/back':
        undergraduate = session.get('undergraduate')
        ranking = list(db.session.execute(account.t, {'undergraduate':undergraduate}))
        return render_template('top.html', name=session.get('name'), undergraduate=undergraduate, ranking=ranking)
    else:
        return render_template('search/result.html', categories=search.categories)

src/app/templates/details/details.html
{% extends "layout.html" %}
{% block title %}
    詳細
{% endblock %}
{% block body %}
<style>
    .back{
        font-size: 150%;
        display:block;
        color:#82ae46;
        text-align:center;
        margin: auto;
        padding-top: 20px;
        
    }
    h3{
        margin-left: 26%;
    }
    table{
        margin: auto;
        width:600px;
    }
    td{
        text-align: center;
    }
    .cart{
        display:block;
        background-color:#82ae46;
        color:#fff;
        width:200px;
        line-height:40px;
        border-radius:4px;
        text-align:center;
        font-size: 20px;
        font-weight: bold;
        margin: auto;
        }
    .cart:hover{
        cursor:pointer;
        }
    .title{
        width: 30%;
    }
</style>
<h3>詳細</h3>
    <table border="3px" bordercolor="#82ae46">
        {% if book_info %}
            <tr>
                <th class="title">タイトル</th><td>{{ book_info.title }}</td>
            </tr>
            <tr>
                <th >著者</th><td>{{ book_info.name }}</td>
            </tr>
            <tr>
                <th>カテゴリー</th><td>{{ book_info.category }}</td>
            </tr>
            <tr>
                <th>本の場所</th><td>{{ book_info.place }}</td>
            </tr>
        {% endif %}
    </table>
    <br>
    <form action="{{url_for('carts.create')}}" method="POST">
        <input type="hidden" value="{{ book_info.id }}" name="book_id">
        <button type="submit" class="cart">カートに追加</button>
    </form>
    <a href="{{url_for('details.back_before_url')}}" class="back">もどる</a>

{% endblock %}