src/app/views/carts.py
from flask import render_template, request, url_for, session, redirect, flash, Blueprint
import datetime

from models import Book, History, User
from database import db
from lib.login_check import login_check


blueprint = Blueprint('carts', __name__)

@blueprint.route('/')
@login_check
def check_cart():
    return render_template('carts/index.html')

# カート画面を表示
@blueprint.route('/cart')
@login_check
def index():
    cart=session.get('cart')
    cart_details = list()
    if type(cart) is dict:
        for key in cart.keys():
            book=Book.query.get(key)
            cart_details.append({ 'id':key, 'name':book.name, 'title':book.title, 'category':book.category })
    return render_template('carts/index.html',cart_details=cart_details)

@blueprint.route('/create',methods=['POST'])
@login_check
def create():
    book_id=request.form.get('book_id') or ""
    cart=session.get('cart')
    if type(cart) is dict:
        cart[book_id]=Book.query.get(book_id).title
    else:
        cart={book_id:Book.query.get(book_id).title}
    session['cart']=cart
    flash('カートに追加しました','success')
    return redirect(url_for('carts.index'))

@blueprint.route('/<string:book_id>/delete',methods=['POST'])
@login_check
def delete(book_id):
    if book_id=='all':
        session.pop('cart',None)
    else:
        cart=session.get('cart')
        cart.pop(book_id,None)
        session['cart']=cart
    flash('本が削除されました','success')
    return redirect(url_for('carts.index'))

@blueprint.route('/insert')
@login_check
def insert():
    carts = session.get('cart')
    user_id = session.get('user_table_id')
    for book_id, title in carts.items():
        if book_id and title:
            history = History(
                book_id = book_id,
                user_id = user_id,
                datetime = datetime.date.today()
            )
            undergraduate = User.query.get(user_id).undergraduate
            if undergraduate == '経済学部':
                Book.query.get(book_id).keizai += 1
            elif undergraduate == '法学部':
                Book.query.get(book_id).hougaku += 1
            elif undergraduate == '理学部':
                Book.query.get(book_id).rigaku += 1
            elif undergraduate == '工学部':
                Book.query.get(book_id).kougaku += 1
            elif undergraduate == '文学部':
                Book.query.get(book_id).bungaku += 1
            elif undergraduate == '医学部':
                Book.query.get(book_id).igaku += 1
            db.session.add(history)
            db.session.commit()
        else:
            flash('最初からやり直してください', 'error')

    session.pop('cart', None)
    flash('本を借りました', 'success')
    return redirect(url_for('carts.index'))

src/app/templates/carts/index.html
{% extends "layout.html" %}
{% block title %}
    カート一覧
{% endblock %}
{% block body %}
    <style>
           h3{
        margin-left: 10%;
        }
        table{
            margin: auto;
            width: 1000px;
            }
        th{
            text-align: center;
        }
        td{
            text-align: center;
        }
        .title{
            width: 50%;
        }
        .category{
            width:8%;
        }
        .name{
            width:12%;
        }
        .delete{
            width: 8%;
        }
        .delete_button {
            position: relative;
            display: inline-block;
            padding: 0.25em 0.5em;
            text-decoration: none;
            color: #FFF;
            background: #b0ca71;/*背景色*/
            border-radius: 4px;/*角の丸み*/
        }
        .all_delete_button{
            position: relative;
            display: inline-block;
            padding: 0.25em 0.5em;
            text-decoration: none;
            color: #FFF;
            background: #b0ca71;/*背景色*/
            border-radius: 4px;/*角の丸み*/
        }
        .all_delete{
            width: 8%;
        }
        /*popup表示させたいコンテンツのレイアウトと位置*/
        #popup{
        width:30%;
        line-height:100px;
        padding:0 4%;
        box-sizing:border-box;
        display:none;
        position:fixed;
        top:50%;
        left:50%;
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        background-color: rgb(185, 184, 184);
        }
        span{
            text-align: center;
        }

        label{
        display:block;
        }
        /*ボタンの装飾*/
        label span{
        display:block;
        background-color:#82ae46;
        color:#fff;
        width:200px;
        line-height:40px;
        border-radius:4px;
        text-align:center;
        margin-left: 74%;
        }
        label span:hover{
        cursor:pointer;
        }
        input[type="checkbox"]{
        display:none;
        }
        /*checkboxがチェックの状態になったらpopupを表示させる*/
        input[type="checkbox"]:checked + #popup{
        display:block;
        }
    </style>

    <script>
        
        function show_popup(){
            if(window.confirm('よろしいですか？')){
                location.href = "{{url_for('carts.insert')}}";
                alert('借りました！')
            }
            else{
                window.alert('キャンセルされました'); // 警告ダイアログを表示
            }
        }

        function show_error_popup(){
            window.alert('図書がありません');
        }

    </script>

    <h3>カート一覧</h3>
    <table border="2" bordercolor="#82ae46">
        <thead>
        <tr>
            <th class="category">カテゴリ</th>
            <th class="title">タイトル</th>
            <th class="name">著者</th>
            <th class="delete">カートから削除</th>
        </tr>    
        </thead>
        <tbody>
            {% if cart_details %}
                {% for cart_detail in cart_details: %}
                    <tr>
                        <td>{{ cart_detail.category }}</td>
                        <td>{{ cart_detail.title }}</td>
                        <td>{{ cart_detail.name }}</td>
                        <td class="delete">
                            <form action="{{url_for('carts.delete',book_id=cart_detail.id)}}" method="POST">
                                <button type="submit" class="delete_button">削除</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td class="all_delete">
                        <form action="{{url_for('carts.delete',book_id='all')}}" method="POST">
                            <button type="submit" class="all_delete_button">全削除</button>
                        </form>
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    <h2>
        <label>
            {% if cart_details %}
                <span type="submit" onClick="show_popup()">借りる</span>
            {% else %}
                <span type="submit" onClick="show_error_popup()">借りる</span>
            {% endif %}
        </label>
    </h2>

{% endblock %}