src/app/views/details.py
from flask import render_template, request, session, Blueprint

from models import Book
from database import db
from views import account, search


blueprint = Blueprint('details', __name__)

@blueprint.route('/<string:id>', methods=['POST'])
def show_details(id):
    book_info = Book.query.get(id)
    global before_url
    before_url = request.referrer
    return render_template('details/details.html', book_info=book_info)

@blueprint.route('/back')
def back_before_url():
    judge = before_url[(before_url.rfind('/')):]
    if judge == '/' or judge == '/back':
        undergraduate = session.get('undergraduate')
        ranking = list(db.session.execute(account.t, {'undergraduate':undergraduate}))
        return render_template('top.html', name=session.get('name'), undergraduate=undergraduate, ranking=ranking)
    else:
        return render_template('search/result.html', categories=search.categories)

src/app/views/search.py
from flask import render_template, request, Blueprint
from sqlalchemy import or_

from models import Book
from lib.login_check import login_check


blueprint = Blueprint('search', __name__)

@blueprint.route('/')
@login_check
def window():
    return render_template('search/window.html')

@blueprint.route('/result', methods=['POST'])
@login_check
def search_result():
    search_category = request.form.get('search_category')
    search_word = request.form.get('search_word')
    global categories
    if not search_category and not search_word:
        categories = Book.query.order_by(Book.category.desc())
    elif not search_category:
        categories = Book.query.order_by(Book.category.desc()).filter(or_(Book.title.like(f'%\\{search_word}%'), Book.name.like(f'%\\{search_word}%')))
    elif not search_word:
        categories = Book.query.order_by(Book.category.desc()).filter(Book.category==search_category)
    else:
        categories = Book.query.order_by(Book.category.desc()).filter(Book.category==search_category).filter(Book.title.like(f'%\\{search_word}%'))
    return render_template('search/result.html', categories=categories)

src/app/templates/search/result.html
{% extends "layout.html" %}
{% block title %}
    検索結果
{% endblock %}

{% block body %}
<style>
        table{
            margin: auto;
            width: 1000px;
        }
        .detail_width{
            width: 7%;
        }
        .detail {
        position: relative;
        display: inline-block;
        padding: 0.25em 0.5em;
        text-decoration: none;
        color: #FFF;
        background: #b0ca71;/*背景色*/
        border-radius: 4px;/*角の丸み*/
        width: 100%;
        }
        .detail:hover{
        cursor:pointer;
        }
        .name{
            width:20%;
        }
        .back{
        font-size: 150%;
        display:block;
        color:#82ae46;
        text-align:center;
        margin: auto;
        padding-top: 20px;
        
        }
</style>
    <h1>検索結果</h1>
    <table border="2" bordercolor="#82ae46">
        <tr class="table_head">
            <th>カテゴリ</th>
            <th>タイトル</th>
            <th>著者</th>
            <th>本の場所</th>
            <th>詳細</th>
        </tr>
        {% for category in categories %}   
        <tr>
            <th>{{ category.category }}</th>
            <th>{{ category.title }}</th>
            <th class="name">{{ category.name }}</th>
            <th>{{ category.place }}</th>
            <form action="{{url_for('details.show_details', id=category.id)}}" method="POST">
                <th class="detail_width"><button value="submit" class="detail">詳細</button></th>
            </form>
        </tr>
        {% endfor %}
    </table>
    <a href="{{url_for('search.window')}}" class="back">もどる</a>
{% endblock %}

src/app/templates/search/window.html
{% extends "layout.html" %}
{% block title %}
    検索窓
{% endblock %}
{% block body %}
<style>
    h2{
        text-align: center;
    }
</style>
<h2>蔵書検索システム</h2>
<div style="margin: 80px;"></div>
<div align = "center">
    <form action="{{url_for('search.search_result')}}" method="POST">
        <input type="text" placeholder="本のタイトル、もしくはキーワードを入力" class="window" name="search_word" style="padding-top: 10px; padding-bottom: 10px; padding-right: 70px; padding-left: 5px; width:400px;">
        <select size="1" class="category" name="search_category" style="padding: 10px; margin-left: 5px; border-radius: 3px;">
            <option value="" style="opacity: none;">カテゴリを選択しない</option>
            <option>教育</option>
            <option>論文</option>
            <option>SF</option>
            <option>ホラー</option>
            <option>恋愛</option>
            <option>ラノベ</option>
        </select>
        <button type="submit" style="margin-left: 40px; padding-left: 10px; padding-right: 10px; padding-top: 6px; padding-bottom: 6px;">検索<i class="fas fa-search" style="margin-left: 8px;"></i></button>
    </form>
</div>
{% endblock %}